### PR TITLE
Make Eclipse stop giving warnings

### LINKED ISSUE #125: Cannot compile without error: package org.junit does not exist
If I try to compile in the build folder with the command:

`ant -Dlibreoffice.home=/lib/libreoffice -Declipse.home=/home/prrvchr/eclipse/commiter-2024-12/eclipse`

I have the following error message:

```
Buildfile: /home/prrvchr/github/loeclipse/build/build.xml
Trying to override old definition of task javac

core.init-env:
    [mkdir] Created dir: /home/prrvchr/github/loeclipse/core/bin/ant/plugins
    [mkdir] Created dir: /home/prrvchr/github/loeclipse/core/bin/ant/classes

java.init-env:

python.init-env:

init-env:

core.version:
     [copy] Copying 1 file to /home/prrvchr/github/loeclipse/build
   [delete] Deleting: /home/prrvchr/github/loeclipse/build/MANIFEST-MF.properties

core.compile:
    [javac] Compiling 200 source files to /home/prrvchr/github/loeclipse/core/bin/ant/classes
    [javac] warning: [options] bootstrap class path is not set in conjunction with -source 8
    [javac]   not setting the bootstrap class path may lead to class files that cannot run on JDK 8
    [javac]     --release 8 is recommended instead of -source 8 -target 1.8 because it sets the bootstrap class path automatically
    [javac] warning: [options] source value 8 is obsolete and will be removed in a future release
    [javac] warning: [options] target value 8 is obsolete and will be removed in a future release
    [javac] warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
    [javac] /home/prrvchr/github/loeclipse/core/source/org/libreoffice/ide/eclipse/core/wizards/pages/ManifestExportPageControllerTest.java:24: error: package org.junit does not exist
    [javac] import static org.junit.Assert.assertEquals;
    [javac]                        ^
    [javac] /home/prrvchr/github/loeclipse/core/source/org/libreoffice/ide/eclipse/core/wizards/pages/ManifestExportPageControllerTest.java:24: error: static import only from classes and interfaces
    [javac] import static org.junit.Assert.assertEquals;
    [javac] ^
    [javac] /home/prrvchr/github/loeclipse/core/source/org/libreoffice/ide/eclipse/core/wizards/pages/ManifestExportPageControllerTest.java:25: error: package org.junit does not exist
    [javac] import static org.junit.Assert.assertFalse;
    [javac]                        ^
    [javac] /home/prrvchr/github/loeclipse/core/source/org/libreoffice/ide/eclipse/core/wizards/pages/ManifestExportPageControllerTest.java:25: error: static import only from classes and interfaces
    [javac] import static org.junit.Assert.assertFalse;
    [javac] ^
    [javac] /home/prrvchr/github/loeclipse/core/source/org/libreoffice/ide/eclipse/core/wizards/pages/ManifestExportPageControllerTest.java:26: error: package org.junit does not exist
    [javac] import static org.junit.Assert.assertNotSame;
    [javac]                        ^
    [javac] /home/prrvchr/github/loeclipse/core/source/org/libreoffice/ide/eclipse/core/wizards/pages/ManifestExportPageControllerTest.java:26: error: static import only from classes and interfaces
    [javac] import static org.junit.Assert.assertNotSame;
    [javac] ^
...
```
In order to be able to compile it seems necessary to add an exclusion on `**/*Test.java` in the build.xml of the core folder.

I will propose a PR to fix this.

### PR DESCRIPTION
**Pull request by prrvchr**
- In order to take advantage of the warnings in Eclipse the **CheckStyle** plugin has been restarted (ie: it was no longer correctly configured) and all files whose code did not meet the requirements of the `/build/checkstyle.xml` file have been updated. It is expected that the file headers (license and copyright) will be modified in order to avoid the last warnings still visible in Eclipse.
- Java 17 is now the minimum version. This seem to be required by the various Eclipse archives that LOEclipse uses (ie: org.eclipse.jdt).
- The template java file `java/source/org/libreoffice/ide/eclipse/java/registration/RegistrationHandler.java.tpl` has been rewritten using generics so that Eclipse warnings stop.
- The test file `core/source/org/libreoffice/ide/eclipse/core/wizards/pages/ManifestExportPageControllerTest.java` has been moved to the `core/source/org/libreoffice/ide/eclipse/core/unittests` folder to allow error-free compilation. This seems to fix  [issue #125](https://github.com/LibreOffice/loeclipse/issues/125).
- All Java methods marked as deprecated have been updated to their replacement method.

Following this PR there are still in the Eclipse problems:
- 21 warnings including 4 TODO.
- 72 infos corresponding to the file headers (license and copyright).

### CODE REVIEW

File: build.properties [hunk 1]
```diff
@@ -1,2 +1,2 @@
-java_source = 1.8
-java_target = 1.8
+java_source = 17
+java_target = 17
```
Comment (smehrbrodt) [inline build.properties:2]: Is it necessary to raise the target version to 17 too?

I'm fine with raising the source level, but would raise the target level only as far as it's really required.

File: python/source/org/libreoffice/ide/eclipse/python/utils/TemplatesHelper.java [hunk 2]
```diff
@@ -103,14 +103,14 @@ public static void copyTemplate(IUnoidlProject pProject, String pTemplateName,
      * @param pClazz the class from which to load the resource file
      * @param pDestPath the path in which the file should be copied, relatively to
      *          the project root.
-     * @param sameFileName the file to be copied to has same name as template or not 
+     * @param pSameFileName the file to be copied to has same name as template or not 
      * @param pArgs additional arguments to pass to the formatter
      */
     public static void copyTemplate(IProject pProject, String pTemplateName,
-        Class<?> pClazz, String pDestPath, boolean sameFileName, Object... pArgs) {
+        Class<?> pClazz, String pDestPath, boolean pSameFileName, Object... pArgs) {
```
Comment (smehrbrodt) [inline python/source/org/libreoffice/ide/eclipse/python/utils/TemplatesHelper.java]: why the `p` prefix here?

File: python/source/org/libreoffice/ide/eclipse/python/PythonBuilder.java [hunk 3]
```diff
@@ -109,22 +109,23 @@ public void fillUnoPackage(UnoPackage pUnoPackage, IUnoidlProject pUnoPrj) {
...
      * directory or one of its sub-folder.
      *
-     * @param pPythonPrj the project from which to get the Python files
-     * @return a list of all the those Python Files
+     * @param pSourceFolder the source folder
+     * @param pPythonFiles the Python files
+     * @param pUnoPrj the project from which to get the Python files
      */
-    private void getPythonFiles(IFolder sourceFolder, ArrayList<IFile> pythonFiles, IUnoidlProject pUnoPrj) {
+    private void getPythonFiles(IFolder pSourceFolder, ArrayList<IFile> pPythonFiles, IUnoidlProject pUnoPrj) {
```
Comment (smehrbrodt) [inline python/source/org/libreoffice/ide/eclipse/python/PythonBuilder.java:119]: Why the `p` prefix here?

**Review by smehrbrodt — CHANGES_REQUESTED** [review]
Looks good!
There are a few places where a `p` prefix has been added to variable names (I commented two, but there are more). What was the motivation for that?

**Comment by prrvchr** [comment]
> Looks good! There are a few places where a `p` prefix has been added to variable names (I commented two, but there are more). What was the motivation for that?

Thank for reviewing.

I followed what was initially done with the `/build/checkstyle.xml` file. 
```
    <module name="ParameterName">
      <property name="format" value="^p[A-Z][a-zA-Z0-9]*$"/>
    </module>

```
It seems that all methods must have parameters starting with `p`, I think like method `p`arameter? Maybe I added this in places that didn't require it? I'll remove it if I see any such cases.

**Comment by smehrbrodt** [comment]
> It seems that all methods must have parameters starting with p, I think like method parameter? Maybe I added this in places that didn't require it? I'll remove it if I see any such cases.

Ok then I would rather update the `checkstyle.xml` file. Adding this prefixes is a bit weird for java code I think.

File: build.properties (hunk 1 above)
Comment (prrvchr) [reply build.properties:2]: I admit that this is a bit beyond me, I am not sufficiently understanding about the compilation of Java modules.
What is certain is that compilation remains possible with 1.8 as it was.

I'll let you decide what to do.

File: python/source/org/libreoffice/ide/eclipse/python/utils/TemplatesHelper.java (hunk 2 above)
Comment (prrvchr) [reply python/source/org/libreoffice/ide/eclipse/python/utils/TemplatesHelper.java]: If we keep this rule, then the parameters of the methods start with `p`.

File: python/source/org/libreoffice/ide/eclipse/python/PythonBuilder.java (hunk 3 above)
Comment (prrvchr) [reply python/source/org/libreoffice/ide/eclipse/python/PythonBuilder.java:119]: If we keep this rule, then the parameters of the methods start with `p`.

**Comment by prrvchr** [comment]
Ok no problem, I can remove this rule and modify the files accordingly?

**Comment by smehrbrodt** [comment]
> Ok no problem, I can remove this rule and modify the files accordingly?

Yes please.

**Review by smehrbrodt — APPROVED** [review]
