### PR TITLE
Fix #8, Fixing Adding UNO Service UX fail

### LINKED ISSUE #8: Adding UNO Service UX fail
I was trying to create an UNO Service w/ loeclipse like this: File > New > Other ... > Libreoffice > UNO Service. It did nothing outside the context of existent LO extension project (in fact, I didn't have any extension project yet). The same issue with UNO interface entry.

This is extremely unintuitive ... so my suggestion is, if at all possible, not to have those two items even offered when there is no extension project. Or have them disabled.

### PR DESCRIPTION
**Pull request by shobhanmandal**
Fixing the Adding of UNO Service/ Interface in UX when the project is not of extension type.

### CODE REVIEW

**Comment by smehrbrodt** [comment]
I still get no warning message when no project is selected :(

File: core/source/org/libreoffice/ide/eclipse/core/actions/UnoTypePulldownAction.java [hunk 1]
```diff
@@ -106,6 +111,14 @@ public boolean isValidSelection(IStructuredSelection pSelection) {
                 }
             }
         }
+        else {
+            Shell shell = Display.getDefault().getActiveShell();
+            MessageDialog.openError(shell, "Error", "Error occured\nYou need to create a LibreOffice project first to use the selection");
```
Comment (smehrbrodt) [inline core/source/org/libreoffice/ide/eclipse/core/actions/UnoTypePulldownAction.java]: You can directly call getShell() here, no need to create a variable for that.
Also please remove the "Error occured\n" from the error message. The dialog already has the type and title "Error".

File: core/source/org/libreoffice/ide/eclipse/core/actions/UnoTypePulldownAction.java [hunk 2]
```diff
@@ -106,6 +111,14 @@ public boolean isValidSelection(IStructuredSelection pSelection) {
...
+        }
+        if(!isValid && projectExist) {
+            Shell shell = Display.getDefault().getActiveShell();
+            MessageDialog.openError(shell, "Error", "Error occured\nThe Selection only works with LibreOffice projects");
```
Comment (smehrbrodt) [inline core/source/org/libreoffice/ide/eclipse/core/actions/UnoTypePulldownAction.java]: Same here.

File: core/source/org/libreoffice/ide/eclipse/core/wizards/NewInterfaceWizard.java [hunk 3]
```diff
@@ -143,6 +145,10 @@ public void init(IWorkbench pWorkbench, IStructuredSelection pSelection) {
                 createPages(resource.getProject());
             }
         }
+        else {
+            Shell shell= getShell();
+            MessageDialog.openError(shell, "Error", "Error occured\nYou need to create a LibreOffice project first to use the selection");
```
Comment (smehrbrodt) [inline core/source/org/libreoffice/ide/eclipse/core/wizards/NewInterfaceWizard.java]: Same here.

File: core/source/org/libreoffice/ide/eclipse/core/wizards/NewInterfaceWizard.java [hunk 4]
```diff
@@ -161,6 +167,11 @@ private void createPages(IProject pProject) {
 
                     addPage(mPage);
                 }
+                else {
+                    Shell shell= getShell();
+                    MessageDialog.openError(shell, "Error", "Error occured\nThe Selection only works with LibreOffice projects");
```
Comment (smehrbrodt) [inline core/source/org/libreoffice/ide/eclipse/core/wizards/NewInterfaceWizard.java]: Same here.

File: core/source/org/libreoffice/ide/eclipse/core/wizards/NewServiceWizard.java [hunk 5]
```diff
@@ -159,6 +162,10 @@ public void init(IWorkbench pWorkbench, IStructuredSelection pSelection) {
                 createPages(resource.getProject());
             }
         }
+        else {
+            Shell shell= getShell();
+            MessageDialog.openError(shell, "Error", "Error occured\nYou need to create a LibreOffice project first to use the selection");
```
Comment (smehrbrodt) [inline core/source/org/libreoffice/ide/eclipse/core/wizards/NewServiceWizard.java]: Same here.

File: core/source/org/libreoffice/ide/eclipse/core/wizards/NewServiceWizard.java [hunk 6]
```diff
@@ -200,6 +207,11 @@ private void createPages(IProject pProject) {
                     mWizardSet.initialize(data);
 
                 }
+                else {
+                    Shell shell= getShell();
+                    MessageDialog.openError(shell, "Error", "Error occured\nThe Selection only works with LibreOffice projects");
```
Comment (smehrbrodt) [inline core/source/org/libreoffice/ide/eclipse/core/wizards/NewServiceWizard.java]: Same here.

**Review by smehrbrodt — CHANGES_REQUESTED** [review]

File: core/source/org/libreoffice/ide/eclipse/core/actions/AbstractPulldownAction.java [hunk 7]
```diff
@@ -57,6 +57,7 @@
 import org.eclipse.jface.viewers.IStructuredSelection;
 import org.eclipse.jface.viewers.StructuredSelection;
 import org.eclipse.jface.wizard.WizardDialog;
+import org.eclipse.jface.dialogs.MessageDialog;
```
Comment (smehrbrodt) [inline core/source/org/libreoffice/ide/eclipse/core/actions/AbstractPulldownAction.java]: Is this still needed?
