### PR TITLE
Fix #62 Null Pointer Exception when trying to export Extension Projects

### LINKED ISSUE #62: Null Pointer Exception when trying to export Extension Projects
A Null Pointer Exception arises under two conditions:
1. There is no Extension project to be exported
2. If no project exists under the Package Explorer (or no Extension project is selected under the Package Explorer) and you go File->Export->LibreOffice package.

!ENTRY org.eclipse.ui 4 0 2018-02-28 17:44:34.662
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NullPointerException
	at org.libreoffice.ide.eclipse.core.gui.PackageContentSelector.getDefaultContent(PackageContentSelector.java:145)
	at org.libreoffice.ide.eclipse.core.gui.PackageContentSelector.loadDefaults(PackageContentSelector.java:109)
	at org.libreoffice.ide.eclipse.core.wizards.pages.UnoPackageExportPage.loadData(UnoPackageExportPage.java:149)
	at org.libreoffice.ide.eclipse.core.wizards.pages.UnoPackageExportPage.createControl(UnoPackageExportPage.java:129)
	at org.eclipse.jface.wizard.Wizard.createPageControls(Wizard.java:175)
	at org.eclipse.jface.wizard.WizardDialog.createPageControls(WizardDialog.java:696)
	at org.eclipse.jface.wizard.WizardDialog.setWizard(WizardDialog.java:1144)
	at org.eclipse.jface.wizard.WizardDialog.updateForPage(WizardDialog.java:1197)
	at org.eclipse.jface.wizard.WizardDialog.lambda$2(WizardDialog.java:1185)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.jface.wizard.WizardDialog.showPage(WizardDialog.java:1185)
	at org.eclipse.jface.wizard.WizardDialog.nextPressed(WizardDialog.java:876)
	at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:419)
	at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:618)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)

### PR DESCRIPTION
**Pull request by shobhanmandal**
The exception was fixed when a particular function which was being called even when there were no Extension Projects was put under proper if condition

### CODE REVIEW

File: core/source/org/libreoffice/ide/eclipse/core/wizards/pages/UnoPackageExportPage.java [hunk 1]
```diff
@@ -145,7 +145,9 @@ private void loadData() {
             i++;
         }
 
-        mContentSelector.loadDefaults();
+        if(selected!=false){
```
Comment (smehrbrodt) [inline core/source/org/libreoffice/ide/eclipse/core/wizards/pages/UnoPackageExportPage.java]: You can shorten the `selected!=false` and write it as `selected`.
Also please keep some space around the braces as the other code does:

`if (selected) {`
